export { default as Landing } from './Landing';
export { default as HomeLayout } from './HomeLayout';
export { default as About } from './About'
export { default as AIResumeBuilder } from './AiResumeBuilder'
export { default as AISocialPostGenerator } from './AISocialPostGenerator'
export { default as Services } from './Services'
export { default as Contact } from './Contact'
export { default as Faq } from './Faq'
export { default as Terms } from './Terms'
export { default as Dashboard } from './Dashboard'
export { default as DepositFunds } from './DepositFunds'
export { default as WithdrawFunds } from './WithdrawFunds'
export { default as ViewPortfolio } from './ViewPortfolio'
export { default as BankTransfer } from './BankTransfer'
export { default as CryptoPage } from './CryptoPage'
export { default as WithdrawForm } from './WithdrawForm'
export { default as StocksPage } from './StocksPage'
export { default as RealEstatePage} from './RealEstatePage'
export { default as DepositFundsForm} from './DepositFundsForm'
export { default as Login} from './Login'
export { default as Register} from './Register'
export { default as UserSettings} from './UserSettings'
export { default as ApprovalSuccess} from './ApprovalSuccess'
export { default as DeleteSuccess} from './DeleteSuccess'
export { default as Transactions} from './Transactions'

